name: CI for dotnet

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "src/SingleOriginSolution/**"
      - ".github/**"
      - ".vscode/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
